"""doc management

Revision ID: feadbe94650d
Revises: 6e1f1f0e772e
Create Date: 2025-11-22 17:55:56.455204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feadbe94650d'
down_revision: Union[str, None] = '6e1f1f0e772e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('income', 'other_expenses', 'life_insurance', 'house_rent', 'NHF', name='document_category'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('relevant_tax_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('fk_documents_user_email_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_relevant_tax_year'), 'documents', ['relevant_tax_year'], unique=False)
    op.create_index(op.f('ix_documents_user_email'), 'documents', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_email'), table_name='documents')
    op.drop_index(op.f('ix_documents_relevant_tax_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
